version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: chitchat

    working_directory: /go/src/github.com/anuragdhingra/lets-chat

    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: run build
          command: |
            dep ensure
            go build -v
